-- =============================================================================
-- Akademi kaynak sicili seed V1 — ADAY kayıtlar (status=candidate).
-- =============================================================================
-- docs/academy/sources_candidates.json'dan üretildi
-- (scripts/academy_probe_sources.ps1 canlı erişim raporu:
-- docs/academy/source_verification.json). ADAY = erişim/lisans onayı DEĞİL;
-- worker gerçek içerik çıkarımını kanıtlayınca status=active yapılır
-- (service_role). Idempotent: on conflict (slug) do nothing.
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, access_method, feed_urls, status) values ('asb', 'American Society of Baking', 'asbe.org', 'US', 'en', array['ekmek_fermantasyon','bilim_arge']::text[], 'association', false, 'rss', '["https://asbe.org/","https://asbe.org/feed/","https://asbe.org/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, access_method, feed_urls, status) values ('bakerpedia', 'BAKERpedia', 'bakerpedia.com', 'US', 'en', array['ekmek_fermantasyon','un_tahil','firin_teknoloji','hijyen_kalite']::text[], 'archive', true, 'rss', '["https://bakerpedia.com/","https://bakerpedia.com/feed/","https://bakerpedia.com/sitemap_index.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, access_method, feed_urls, status) values ('lesaffre', 'Lesaffre', 'lesaffre.com', 'FR', 'en', array['ekmek_fermantasyon']::text[], 'vendor', true, 'rss', '["https://www.lesaffre.com/","https://www.lesaffre.com/feed/","https://www.lesaffre.com/sitemap_index.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, access_method, feed_urls, status) values ('lallemand_baking', 'Lallemand Baking', 'lallemandbaking.com', 'CA', 'en', array['ekmek_fermantasyon']::text[], 'vendor', true, 'rss', '["https://www.lallemandbaking.com/en/global/","https://www.lallemandbaking.com/feed/","https://www.lallemandbaking.com/sitemap_index.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, access_method, feed_urls, status) values ('tusaf', 'Türkiye Un Sanayicileri Federasyonu (TUSAF)', 'tusaf.org', 'TR', 'tr', array['un_tahil','sektor_gundemi']::text[], 'association', false, 'rss', '["https://www.tusaf.org/","https://www.tusaf.org/feed/","https://www.tusaf.org/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, access_method, feed_urls, status) values ('tabader', 'Tahıl ve Bakliyat İşleme Teknolojileri Derneği (TABADER)', 'tabader.org', 'TR', 'tr', array['un_tahil']::text[], 'association', false, 'rss', '["https://tabader.org/","https://tabader.org/feed/","https://tabader.org/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, access_method, feed_urls, status) values ('icc_cereal', 'International Association for Cereal Science and Technology (ICC)', 'icc.or.at', 'AT', 'en', array['un_tahil','bilim_arge']::text[], 'association', false, 'rss', '["https://icc.or.at/","https://icc.or.at/feed/","https://icc.or.at/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, access_method, feed_urls, status) values ('ksu_grain', 'Kansas State University Grain Science', 'grains.k-state.edu', 'US', 'en', array['un_tahil','bilim_arge']::text[], 'academic', false, 'rss', '["https://www.grains.k-state.edu/","https://www.grains.k-state.edu/feed/","https://www.k-state.edu/media/newsreleases/rss.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, access_method, feed_urls, status) values ('pakmaya', 'Pakmaya', 'pakmaya.com.tr', 'TR', 'tr', array['turk_urunleri','ekmek_fermantasyon']::text[], 'vendor', true, 'rss', '["https://www.pakmaya.com.tr/","https://www.pakmaya.com.tr/feed/","https://www.pakmaya.com.tr/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, access_method, feed_urls, status) values ('soke_un', 'Söke Un', 'soke.com.tr', 'TR', 'tr', array['turk_urunleri','un_tahil']::text[], 'vendor', true, 'rss', '["https://www.soke.com.tr/","https://www.soke.com.tr/feed/","https://www.soke.com.tr/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, access_method, feed_urls, status) values ('sinangil', 'Sinangil Un', 'sinangil.com.tr', 'TR', 'tr', array['turk_urunleri','un_tahil']::text[], 'vendor', true, 'rss', '["https://www.sinangil.com.tr/","https://www.sinangil.com.tr/feed/","https://www.sinangil.com.tr/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, access_method, feed_urls, status) values ('ekmek_dunyasi', 'Ekmek Dünyası', 'ekmekdunyasi.com', 'TR', 'tr', array['turk_urunleri','sektor_gundemi']::text[], 'news', false, 'rss', '["https://www.ekmekdunyasi.com/","https://www.ekmekdunyasi.com/feed/","https://www.ekmekdunyasi.com/rss.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, access_method, feed_urls, status) values ('puratos', 'Puratos', 'puratos.com', 'BE', 'en', array['pastacilik','ekmek_fermantasyon']::text[], 'vendor', true, 'rss', '["https://www.puratos.com/","https://www.puratos.com/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, access_method, feed_urls, status) values ('ireks', 'IREKS', 'ireks.com', 'DE', 'de', array['pastacilik','ekmek_fermantasyon']::text[], 'vendor', true, 'rss', '["https://www.ireks.com/","https://www.ireks.de/","https://www.ireks.com/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, access_method, feed_urls, status) values ('zeelandia', 'Zeelandia', 'zeelandia.com', 'NL', 'en', array['pastacilik']::text[], 'vendor', true, 'rss', '["https://www.zeelandia.com/","https://www.zeelandia.com/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, access_method, feed_urls, status) values ('dawn_foods', 'Dawn Foods', 'dawnfoods.com', 'US', 'en', array['pastacilik']::text[], 'vendor', true, 'rss', '["https://www.dawnfoods.com/","https://www.dawnfoods.com/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, access_method, feed_urls, status) values ('miwe', 'MIWE', 'miwe.de', 'DE', 'de', array['firin_teknoloji']::text[], 'vendor', true, 'rss', '["https://www.miwe.de/","https://www.miwe.com/","https://www.miwe.de/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, access_method, feed_urls, status) values ('fritsch', 'FRITSCH Bakery Technologies', 'fritsch-group.com', 'DE', 'en', array['firin_teknoloji']::text[], 'vendor', true, 'rss', '["https://www.fritsch-group.com/","https://www.fritsch-group.com/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, access_method, feed_urls, status) values ('rondo', 'RONDO', 'rondo-online.com', 'CH', 'en', array['firin_teknoloji','pastacilik']::text[], 'vendor', true, 'rss', '["https://www.rondo-online.com/","https://www.rondo-online.com/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, access_method, feed_urls, status) values ('buhler', 'Bühler Group', 'buhlergroup.com', 'CH', 'en', array['firin_teknoloji','un_tahil']::text[], 'vendor', true, 'rss', '["https://www.buhlergroup.com/","https://www.buhlergroup.com/content/buhlergroup/global/en/homepage.html","https://www.buhlergroup.com/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, access_method, feed_urls, status) values ('tarim_orman', 'T.C. Tarım ve Orman Bakanlığı', 'tarimorman.gov.tr', 'TR', 'tr', array['hijyen_kalite','sektor_gundemi']::text[], 'gov', false, 'rss', '["https://www.tarimorman.gov.tr/","https://www.tarimorman.gov.tr/Rss","https://www.tarimorman.gov.tr/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, access_method, feed_urls, status) values ('aib', 'AIB International', 'aibinternational.com', 'US', 'en', array['hijyen_kalite']::text[], 'edu', true, 'rss', '["https://www.aibinternational.com/","https://www.aibinternational.com/feed/","https://www.aibinternational.com/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, access_method, feed_urls, status) values ('campden_bri', 'Campden BRI', 'campdenbri.co.uk', 'UK', 'en', array['hijyen_kalite','bilim_arge']::text[], 'academic', true, 'rss', '["https://www.campdenbri.co.uk/","https://www.campdenbri.co.uk/rss/all.xml","https://www.campdenbri.co.uk/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, access_method, feed_urls, status) values ('efsa', 'European Food Safety Authority (EFSA)', 'efsa.europa.eu', 'EU', 'en', array['hijyen_kalite','bilim_arge']::text[], 'gov', false, 'rss', '["https://www.efsa.europa.eu/","https://www.efsa.europa.eu/en/rss","https://www.efsa.europa.eu/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, access_method, feed_urls, status) values ('kosgeb', 'KOSGEB', 'kosgeb.gov.tr', 'TR', 'tr', array['isletme']::text[], 'gov', false, 'rss', '["https://www.kosgeb.gov.tr/","https://www.kosgeb.gov.tr/site/tr/genel/rss","https://www.kosgeb.gov.tr/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, access_method, feed_urls, status) values ('tesk', 'Türkiye Esnaf ve Sanatkarları Konfederasyonu (TESK)', 'tesk.org.tr', 'TR', 'tr', array['isletme','sektor_gundemi']::text[], 'association', false, 'rss', '["https://www.tesk.org.tr/","https://www.tesk.org.tr/feed/","https://www.tesk.org.tr/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, access_method, feed_urls, status) values ('rba', 'Retail Bakers of America', 'retailbakersofamerica.org', 'US', 'en', array['isletme']::text[], 'association', false, 'rss', '["https://retailbakersofamerica.org/","https://retailbakersofamerica.org/feed/","https://retailbakersofamerica.org/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, access_method, feed_urls, status) values ('tuik', 'TÜİK', 'tuik.gov.tr', 'TR', 'tr', array['isletme','sektor_gundemi']::text[], 'gov', false, 'rss', '["https://www.tuik.gov.tr/","https://data.tuik.gov.tr/RssFeed/GetRssFeed?dilId=1","https://www.tuik.gov.tr/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, access_method, feed_urls, status) values ('tmo', 'Toprak Mahsulleri Ofisi (TMO)', 'tmo.gov.tr', 'TR', 'tr', array['sektor_gundemi','un_tahil']::text[], 'gov', false, 'rss', '["https://www.tmo.gov.tr/","https://www.tmo.gov.tr/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, access_method, feed_urls, status) values ('bbm_magazine', 'BBM Magazine (Değirmencilik/Bakery)', 'bbm-magazine.com', 'TR', 'en', array['sektor_gundemi','un_tahil']::text[], 'news', false, 'rss', '["https://www.bbm-magazine.com/","https://www.bbm-magazine.com/feed/","https://www.bbm-magazine.com/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, access_method, feed_urls, status) values ('baking_business', 'Baking Business (Sosland)', 'bakingbusiness.com', 'US', 'en', array['sektor_gundemi']::text[], 'news', false, 'rss', '["https://www.bakingbusiness.com/","https://www.bakingbusiness.com/rss/topic/298","https://www.bakingbusiness.com/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, access_method, feed_urls, status) values ('british_baker', 'British Baker', 'bakeryinfo.co.uk', 'UK', 'en', array['sektor_gundemi','pastacilik']::text[], 'news', false, 'rss', '["https://www.bakeryinfo.co.uk/","https://www.bakeryinfo.co.uk/rss","https://www.bakeryinfo.co.uk/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, access_method, feed_urls, status) values ('tubitak_mam', 'TÜBİTAK MAM', 'mam.tubitak.gov.tr', 'TR', 'tr', array['bilim_arge']::text[], 'academic', false, 'rss', '["https://mam.tubitak.gov.tr/","https://mam.tubitak.gov.tr/tr/haberler","https://mam.tubitak.gov.tr/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, access_method, feed_urls, status) values ('gida_dergisi', 'GIDA / The Journal of Food (DergiPark)', 'dergipark.org.tr', 'TR', 'tr', array['bilim_arge','hijyen_kalite']::text[], 'academic', false, 'rss', '["https://dergipark.org.tr/tr/pub/gida","https://dergipark.org.tr/tr/pub/gida/rss","https://dergipark.org.tr/tr/pub/gida/archive"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, access_method, feed_urls, status) values ('wageningen', 'Wageningen University & Research', 'wur.nl', 'NL', 'en', array['bilim_arge']::text[], 'academic', false, 'rss', '["https://www.wur.nl/en.htm","https://www.wur.nl/en/rss.htm","https://www.wur.nl/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, access_method, feed_urls, status) values ('inrae', 'INRAE', 'inrae.fr', 'FR', 'fr', array['bilim_arge']::text[], 'academic', false, 'rss', '["https://www.inrae.fr/","https://www.inrae.fr/actualites/flux.rss","https://www.inrae.fr/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, access_method, feed_urls, status) values ('sfbi', 'San Francisco Baking Institute (SFBI)', 'sfbi.com', 'US', 'en', array['ustalik_dunya','ekmek_fermantasyon']::text[], 'edu', true, 'rss', '["https://sfbi.com/","https://sfbi.com/feed/","https://sfbi.com/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, access_method, feed_urls, status) values ('richemont', 'Richemont Fachschule', 'richemont.swiss', 'CH', 'de', array['ustalik_dunya','pastacilik']::text[], 'edu', true, 'rss', '["https://richemont.swiss/","https://richemont.swiss/feed/","https://richemont.swiss/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, access_method, feed_urls, status) values ('bbga', 'Bread Bakers Guild of America', 'bbga.org', 'US', 'en', array['ustalik_dunya','ekmek_fermantasyon']::text[], 'association', false, 'rss', '["https://www.bbga.org/","https://www.bbga.org/feed/","https://www.bbga.org/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, access_method, feed_urls, status) values ('king_arthur_pro', 'King Arthur Baking Professional', 'kingarthurbaking.com', 'US', 'en', array['ustalik_dunya','pastacilik']::text[], 'vendor', true, 'rss', '["https://www.kingarthurbaking.com/pro","https://www.kingarthurbaking.com/blog/feed","https://www.kingarthurbaking.com/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, access_method, feed_urls, status) values ('halk_ekmek_ist', 'İstanbul Halk Ekmek', 'ihe.istanbul', 'TR', 'tr', array['turk_urunleri','sektor_gundemi']::text[], 'gov', false, 'rss', '["https://www.ihe.istanbul/","https://www.ihe.istanbul/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;

-- Bot–kaynak eşleştirme: kaynak konuları → bot anahtarı (idempotent).
insert into public.academy_bot_sources (bot_key, source_id, weight)
select t.topic, s.id, 100
from public.academy_sources s
cross join lateral unnest(s.topics) as t(topic)
join public.academy_bot_profiles b on b.bot_key = t.topic
on conflict (bot_key, source_id) do nothing;
