-- =============================================================================
-- Akademi kaynak sicili seed V1 — ADAY kayıtlar (status=candidate).
-- =============================================================================
-- docs/academy/sources_candidates.json'dan üretildi (113 aday; probe raporu
-- docs/academy/source_verification.json). ADAY != aktif: worker gerçek
-- makale çıkarımını kanıtlayınca status=active olur. Aynı yayıncı grubu
-- publisher_group ile işaretlidir (bağımsız teyit SAYILMAZ). Idempotent.
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('asb', 'American Society of Baking', 'asbe.org', 'US', 'en', array['ekmek_fermantasyon','bilim_arge']::text[], 'association', false, null, 'rss', '["https://asbe.org/","https://asbe.org/feed/","https://asbe.org/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('bakerpedia', 'BAKERpedia', 'bakerpedia.com', 'US', 'en', array['ekmek_fermantasyon','un_tahil','firin_teknoloji','hijyen_kalite']::text[], 'archive', true, null, 'rss', '["https://bakerpedia.com/","https://bakerpedia.com/feed/","https://bakerpedia.com/sitemap_index.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('lesaffre', 'Lesaffre', 'lesaffre.com', 'FR', 'en', array['ekmek_fermantasyon']::text[], 'vendor', true, null, 'rss', '["https://www.lesaffre.com/","https://www.lesaffre.com/feed/","https://www.lesaffre.com/sitemap_index.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('lallemand_baking', 'Lallemand Baking', 'lallemandbaking.com', 'CA', 'en', array['ekmek_fermantasyon']::text[], 'vendor', true, null, 'rss', '["https://www.lallemandbaking.com/en/global/","https://www.lallemandbaking.com/feed/","https://www.lallemandbaking.com/sitemap_index.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('tusaf', 'Türkiye Un Sanayicileri Federasyonu (TUSAF)', 'tusaf.org', 'TR', 'tr', array['un_tahil','sektor_gundemi']::text[], 'association', false, null, 'rss', '["https://www.tusaf.org/","https://www.tusaf.org/feed/","https://www.tusaf.org/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('tabader', 'Tahıl ve Bakliyat İşleme Teknolojileri Derneği (TABADER)', 'tabader.org', 'TR', 'tr', array['un_tahil']::text[], 'association', false, null, 'rss', '["https://tabader.org/","https://tabader.org/feed/","https://tabader.org/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('icc_cereal', 'International Association for Cereal Science and Technology (ICC)', 'icc.or.at', 'AT', 'en', array['un_tahil','bilim_arge']::text[], 'association', false, null, 'rss', '["https://icc.or.at/","https://icc.or.at/feed/","https://icc.or.at/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('ksu_grain', 'Kansas State University Grain Science', 'grains.k-state.edu', 'US', 'en', array['un_tahil','bilim_arge']::text[], 'academic', false, null, 'rss', '["https://www.grains.k-state.edu/","https://www.grains.k-state.edu/feed/","https://www.k-state.edu/media/newsreleases/rss.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('pakmaya', 'Pakmaya', 'pakmaya.com.tr', 'TR', 'tr', array['turk_urunleri','ekmek_fermantasyon']::text[], 'vendor', true, null, 'rss', '["https://www.pakmaya.com.tr/","https://www.pakmaya.com.tr/feed/","https://www.pakmaya.com.tr/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('soke_un', 'Söke Un', 'soke.com.tr', 'TR', 'tr', array['turk_urunleri','un_tahil']::text[], 'vendor', true, null, 'rss', '["https://www.soke.com.tr/","https://www.soke.com.tr/feed/","https://www.soke.com.tr/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('sinangil', 'Sinangil Un', 'sinangil.com.tr', 'TR', 'tr', array['turk_urunleri','un_tahil']::text[], 'vendor', true, null, 'rss', '["https://www.sinangil.com.tr/","https://www.sinangil.com.tr/feed/","https://www.sinangil.com.tr/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('ekmek_dunyasi', 'Ekmek Dünyası', 'ekmekdunyasi.com', 'TR', 'tr', array['turk_urunleri','sektor_gundemi']::text[], 'news', false, null, 'rss', '["https://www.ekmekdunyasi.com/","https://www.ekmekdunyasi.com/feed/","https://www.ekmekdunyasi.com/rss.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('puratos', 'Puratos', 'puratos.com', 'BE', 'en', array['pastacilik','ekmek_fermantasyon']::text[], 'vendor', true, null, 'rss', '["https://www.puratos.com/","https://www.puratos.com/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('ireks', 'IREKS', 'ireks.com', 'DE', 'de', array['pastacilik','ekmek_fermantasyon']::text[], 'vendor', true, null, 'rss', '["https://www.ireks.com/","https://www.ireks.de/","https://www.ireks.com/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('zeelandia', 'Zeelandia', 'zeelandia.com', 'NL', 'en', array['pastacilik']::text[], 'vendor', true, null, 'rss', '["https://www.zeelandia.com/","https://www.zeelandia.com/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('dawn_foods', 'Dawn Foods', 'dawnfoods.com', 'US', 'en', array['pastacilik']::text[], 'vendor', true, null, 'rss', '["https://www.dawnfoods.com/","https://www.dawnfoods.com/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('miwe', 'MIWE', 'miwe.de', 'DE', 'de', array['firin_teknoloji']::text[], 'vendor', true, null, 'rss', '["https://www.miwe.de/","https://www.miwe.com/","https://www.miwe.de/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('fritsch', 'FRITSCH Bakery Technologies', 'fritsch-group.com', 'DE', 'en', array['firin_teknoloji']::text[], 'vendor', true, null, 'rss', '["https://www.fritsch-group.com/","https://www.fritsch-group.com/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('rondo', 'RONDO', 'rondo-online.com', 'CH', 'en', array['firin_teknoloji','pastacilik']::text[], 'vendor', true, null, 'rss', '["https://www.rondo-online.com/","https://www.rondo-online.com/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('buhler', 'Bühler Group', 'buhlergroup.com', 'CH', 'en', array['firin_teknoloji','un_tahil']::text[], 'vendor', true, null, 'rss', '["https://www.buhlergroup.com/","https://www.buhlergroup.com/content/buhlergroup/global/en/homepage.html","https://www.buhlergroup.com/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('tarim_orman', 'T.C. Tarım ve Orman Bakanlığı', 'tarimorman.gov.tr', 'TR', 'tr', array['hijyen_kalite','sektor_gundemi']::text[], 'gov', false, null, 'rss', '["https://www.tarimorman.gov.tr/","https://www.tarimorman.gov.tr/Rss","https://www.tarimorman.gov.tr/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('aib', 'AIB International', 'aibinternational.com', 'US', 'en', array['hijyen_kalite']::text[], 'edu', true, null, 'rss', '["https://www.aibinternational.com/","https://www.aibinternational.com/feed/","https://www.aibinternational.com/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('campden_bri', 'Campden BRI', 'campdenbri.co.uk', 'UK', 'en', array['hijyen_kalite','bilim_arge']::text[], 'academic', true, null, 'rss', '["https://www.campdenbri.co.uk/","https://www.campdenbri.co.uk/rss/all.xml","https://www.campdenbri.co.uk/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('efsa', 'European Food Safety Authority (EFSA)', 'efsa.europa.eu', 'EU', 'en', array['hijyen_kalite','bilim_arge']::text[], 'gov', false, null, 'rss', '["https://www.efsa.europa.eu/","https://www.efsa.europa.eu/en/rss","https://www.efsa.europa.eu/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('kosgeb', 'KOSGEB', 'kosgeb.gov.tr', 'TR', 'tr', array['isletme']::text[], 'gov', false, null, 'rss', '["https://www.kosgeb.gov.tr/","https://www.kosgeb.gov.tr/site/tr/genel/rss","https://www.kosgeb.gov.tr/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('tesk', 'Türkiye Esnaf ve Sanatkarları Konfederasyonu (TESK)', 'tesk.org.tr', 'TR', 'tr', array['isletme','sektor_gundemi']::text[], 'association', false, null, 'rss', '["https://www.tesk.org.tr/","https://www.tesk.org.tr/feed/","https://www.tesk.org.tr/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('rba', 'Retail Bakers of America', 'retailbakersofamerica.org', 'US', 'en', array['isletme']::text[], 'association', false, null, 'rss', '["https://retailbakersofamerica.org/","https://retailbakersofamerica.org/feed/","https://retailbakersofamerica.org/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('tuik', 'TÜİK', 'tuik.gov.tr', 'TR', 'tr', array['isletme','sektor_gundemi']::text[], 'gov', false, null, 'rss', '["https://www.tuik.gov.tr/","https://data.tuik.gov.tr/RssFeed/GetRssFeed?dilId=1","https://www.tuik.gov.tr/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('tmo', 'Toprak Mahsulleri Ofisi (TMO)', 'tmo.gov.tr', 'TR', 'tr', array['sektor_gundemi','un_tahil']::text[], 'gov', false, null, 'rss', '["https://www.tmo.gov.tr/","https://www.tmo.gov.tr/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('bbm_magazine', 'BBM Magazine (Değirmencilik/Bakery)', 'bbm-magazine.com', 'TR', 'en', array['sektor_gundemi','un_tahil']::text[], 'news', false, 'parantez', 'rss', '["https://www.bbm-magazine.com/","https://www.bbm-magazine.com/feed/","https://www.bbm-magazine.com/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('baking_business', 'Baking Business (Sosland)', 'bakingbusiness.com', 'US', 'en', array['sektor_gundemi','isletme']::text[], 'news', false, 'sosland', 'rss', '["https://www.bakingbusiness.com/","https://www.bakingbusiness.com/rss/topic/298","https://www.bakingbusiness.com/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('british_baker', 'British Baker', 'bakeryinfo.co.uk', 'UK', 'en', array['sektor_gundemi','pastacilik']::text[], 'news', false, null, 'rss', '["https://www.bakeryinfo.co.uk/","https://www.bakeryinfo.co.uk/rss","https://www.bakeryinfo.co.uk/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('tubitak_mam', 'TÜBİTAK MAM', 'mam.tubitak.gov.tr', 'TR', 'tr', array['bilim_arge']::text[], 'academic', false, null, 'rss', '["https://mam.tubitak.gov.tr/","https://mam.tubitak.gov.tr/tr/haberler","https://mam.tubitak.gov.tr/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('gida_dergisi', 'GIDA / The Journal of Food (DergiPark)', 'dergipark.org.tr', 'TR', 'tr', array['bilim_arge','hijyen_kalite']::text[], 'academic', false, null, 'rss', '["https://dergipark.org.tr/tr/pub/gida","https://dergipark.org.tr/tr/pub/gida/rss","https://dergipark.org.tr/tr/pub/gida/archive"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('wageningen', 'Wageningen University & Research', 'wur.nl', 'NL', 'en', array['bilim_arge']::text[], 'academic', false, null, 'rss', '["https://www.wur.nl/en.htm","https://www.wur.nl/en/rss.htm","https://www.wur.nl/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('inrae', 'INRAE', 'inrae.fr', 'FR', 'fr', array['bilim_arge']::text[], 'academic', false, null, 'rss', '["https://www.inrae.fr/","https://www.inrae.fr/actualites/flux.rss","https://www.inrae.fr/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('sfbi', 'San Francisco Baking Institute (SFBI)', 'sfbi.com', 'US', 'en', array['ustalik_dunya','ekmek_fermantasyon']::text[], 'edu', true, null, 'rss', '["https://sfbi.com/","https://sfbi.com/feed/","https://sfbi.com/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('richemont', 'Richemont Fachschule', 'richemont.swiss', 'CH', 'de', array['ustalik_dunya','pastacilik']::text[], 'edu', true, null, 'rss', '["https://richemont.swiss/","https://richemont.swiss/feed/","https://richemont.swiss/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('bbga', 'Bread Bakers Guild of America', 'bbga.org', 'US', 'en', array['ustalik_dunya','ekmek_fermantasyon']::text[], 'association', false, null, 'rss', '["https://www.bbga.org/","https://www.bbga.org/feed/","https://www.bbga.org/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('king_arthur_pro', 'King Arthur Baking Professional', 'kingarthurbaking.com', 'US', 'en', array['ustalik_dunya','pastacilik']::text[], 'vendor', true, null, 'rss', '["https://www.kingarthurbaking.com/pro","https://www.kingarthurbaking.com/blog/feed","https://www.kingarthurbaking.com/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('halk_ekmek_ist', 'İstanbul Halk Ekmek', 'ihe.istanbul', 'TR', 'tr', array['turk_urunleri','sektor_gundemi']::text[], 'gov', false, null, 'rss', '["https://www.ihe.istanbul/","https://www.ihe.istanbul/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('aacc_cereals', 'Cereals & Grains Association (AACC)', 'cerealsgrains.org', 'US', 'en', array['un_tahil','bilim_arge']::text[], 'association', false, null, 'rss', '["https://www.cerealsgrains.org/","https://www.cerealsgrains.org/news/Pages/default.aspx","https://www.cerealsgrains.org/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('world_grain', 'World Grain (Sosland)', 'world-grain.com', 'US', 'en', array['un_tahil','sektor_gundemi']::text[], 'news', false, 'sosland', 'rss', '["https://www.world-grain.com/","https://www.world-grain.com/rss/articles","https://www.world-grain.com/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('miller_magazine', 'Miller Magazine / Değirmenci Dergisi', 'millermagazine.com', 'TR', 'en', array['un_tahil','sektor_gundemi']::text[], 'news', false, 'parantez', 'rss', '["https://millermagazine.com/","https://millermagazine.com/feed/","https://millermagazine.com/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('bakeryandsnacks', 'BakeryAndSnacks (William Reed)', 'bakeryandsnacks.com', 'UK', 'en', array['sektor_gundemi','pastacilik']::text[], 'news', false, null, 'rss', '["https://www.bakeryandsnacks.com/","https://www.bakeryandsnacks.com/Info/Latest-News","https://www.bakeryandsnacks.com/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('bake_mag', 'Bake Magazine (Sosland)', 'bakemag.com', 'US', 'en', array['pastacilik','isletme']::text[], 'news', false, 'sosland', 'rss', '["https://www.bakemag.com/","https://www.bakemag.com/rss/articles","https://www.bakemag.com/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('gida_teknolojisi', 'Gıda Teknolojisi Dergisi', 'gidateknolojisi.com.tr', 'TR', 'tr', array['bilim_arge','hijyen_kalite','sektor_gundemi']::text[], 'news', false, null, 'rss', '["https://www.gidateknolojisi.com.tr/","https://www.gidateknolojisi.com.tr/feed/","https://www.gidateknolojisi.com.tr/rss.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('tff_firincilar', 'Türkiye Fırıncılar Federasyonu', 'tff.org.tr', 'TR', 'tr', array['sektor_gundemi','isletme','turk_urunleri']::text[], 'association', false, null, 'rss', '["https://www.tff.org.tr/","https://tff.org.tr/","https://www.tff.org.tr/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('ist_firincilar_odasi', 'İstanbul Fırıncılar Odası', 'istanbulfirincilarodasi.org.tr', 'TR', 'tr', array['isletme','turk_urunleri']::text[], 'association', false, null, 'rss', '["https://www.istanbulfirincilarodasi.org.tr/","https://istanbulfirincilarodasi.org.tr/"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('ticaret_bakanligi', 'T.C. Ticaret Bakanlığı', 'ticaret.gov.tr', 'TR', 'tr', array['isletme','sektor_gundemi']::text[], 'gov', false, null, 'rss', '["https://www.ticaret.gov.tr/","https://www.ticaret.gov.tr/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('fao', 'FAO (BM Gıda ve Tarım Örgütü)', 'fao.org', 'INT', 'en', array['un_tahil','sektor_gundemi','hijyen_kalite']::text[], 'gov', false, null, 'rss', '["https://www.fao.org/newsroom/en","https://www.fao.org/feeds/fao-newsroom-rss","https://www.fao.org/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('codex', 'Codex Alimentarius', 'fao.org', 'INT', 'en', array['hijyen_kalite']::text[], 'gov', false, 'fao', 'rss', '["https://www.fao.org/fao-who-codexalimentarius/news-and-events/en/"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('who_food', 'WHO Food Safety', 'who.int', 'INT', 'en', array['hijyen_kalite']::text[], 'gov', false, null, 'rss', '["https://www.who.int/health-topics/food-safety","https://www.who.int/rss-feeds/news-english.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('fda_food', 'U.S. FDA Food', 'fda.gov', 'US', 'en', array['hijyen_kalite']::text[], 'gov', false, null, 'rss', '["https://www.fda.gov/food","https://www.fda.gov/about-fda/contact-fda/stay-informed/rss-feeds/food/rss.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('bfr', 'BfR (Alman Risk Değerlendirme Enstitüsü)', 'bfr.bund.de', 'DE', 'de', array['hijyen_kalite','bilim_arge']::text[], 'gov', false, null, 'rss', '["https://www.bfr.bund.de/de/start.html","https://www.bfr.bund.de/de/rss.html"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('mri_bund', 'Max Rubner-Institut (Detmold tahıl)', 'mri.bund.de', 'DE', 'de', array['un_tahil','bilim_arge']::text[], 'academic', false, null, 'rss', '["https://www.mri.bund.de/","https://www.mri.bund.de/de/aktuelles/"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('cimmyt', 'CIMMYT (Buğday Araştırma)', 'cimmyt.org', 'MX', 'en', array['un_tahil','bilim_arge']::text[], 'academic', false, null, 'rss', '["https://www.cimmyt.org/","https://www.cimmyt.org/feed/","https://www.cimmyt.org/sitemap_index.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('uswheat', 'U.S. Wheat Associates', 'uswheat.org', 'US', 'en', array['un_tahil','sektor_gundemi']::text[], 'association', false, null, 'rss', '["https://www.uswheat.org/","https://www.uswheat.org/feed/","https://www.uswheat.org/sitemap_index.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('mdpi_foods', 'MDPI Foods (açık erişim dergi)', 'mdpi.com', 'CH', 'en', array['bilim_arge','hijyen_kalite']::text[], 'academic', false, null, 'rss', '["https://www.mdpi.com/journal/foods","https://www.mdpi.com/rss/journal/foods"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('inbp', 'INBP (Fransa Ulusal Fırıncılık Enstitüsü)', 'inbp.com', 'FR', 'fr', array['ustalik_dunya','pastacilik']::text[], 'edu', true, null, 'rss', '["https://www.inbp.com/","https://www.inbp.com/actualites/","https://www.inbp.com/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('akademie_weinheim', 'Akademie Deutsches Bäckerhandwerk Weinheim', 'akademie-weinheim.de', 'DE', 'de', array['ustalik_dunya']::text[], 'edu', true, null, 'rss', '["https://www.akademie-weinheim.de/","https://www.akademie-weinheim.de/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('baeckerhandwerk', 'Zentralverband des Deutschen Bäckerhandwerks', 'baeckerhandwerk.de', 'DE', 'de', array['sektor_gundemi','ustalik_dunya','isletme']::text[], 'association', false, null, 'rss', '["https://www.baeckerhandwerk.de/","https://www.baeckerhandwerk.de/feed/","https://www.baeckerhandwerk.de/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('webbaecker', 'WebBäcker / ABZ haber', 'webbaecker.de', 'DE', 'de', array['sektor_gundemi']::text[], 'news', false, null, 'rss', '["https://www.webbaecker.de/","https://www.webbaecker.de/feed/"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('boulangerie_conf', 'Confédération Nationale de la Boulangerie (FR)', 'boulangerie.org', 'FR', 'fr', array['sektor_gundemi','ustalik_dunya']::text[], 'association', false, null, 'rss', '["https://www.boulangerie.org/","https://www.boulangerie.org/feed/"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('ab_mauri', 'AB Mauri', 'abmauri.com', 'UK', 'en', array['ekmek_fermantasyon']::text[], 'vendor', true, null, 'rss', '["https://www.abmauri.com/","https://www.abmauri.com/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('angel_yeast', 'Angel Yeast', 'angelyeast.com', 'CN', 'en', array['ekmek_fermantasyon']::text[], 'vendor', true, null, 'rss', '["https://en.angelyeast.com/","https://en.angelyeast.com/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('bakels', 'Bakels Group', 'bakels.com', 'CH', 'en', array['pastacilik','ekmek_fermantasyon']::text[], 'vendor', true, null, 'rss', '["https://www.bakels.com/","https://www.bakels.com/sitemap_index.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('corbion', 'Corbion (fermantasyon/raf ömrü)', 'corbion.com', 'NL', 'en', array['hijyen_kalite','ekmek_fermantasyon']::text[], 'vendor', true, null, 'rss', '["https://www.corbion.com/","https://www.corbion.com/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('novonesis_baking', 'Novonesis (enzim/baking)', 'novonesis.com', 'DK', 'en', array['bilim_arge','ekmek_fermantasyon']::text[], 'vendor', true, null, 'rss', '["https://www.novonesis.com/","https://www.novonesis.com/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('wp_bakery', 'WP Bakery Group', 'wp-l.com', 'DE', 'de', array['firin_teknoloji']::text[], 'vendor', true, null, 'rss', '["https://www.wp-l.com/","https://www.wp-l.com/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('wachtel', 'Wachtel (fırınlar)', 'wachtel.de', 'DE', 'de', array['firin_teknoloji']::text[], 'vendor', true, null, 'rss', '["https://www.wachtel.de/","https://www.wachtel.de/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('sveba_dahlen', 'Sveba Dahlen', 'sveba-dahlen.com', 'SE', 'en', array['firin_teknoloji']::text[], 'vendor', true, null, 'rss', '["https://www.sveba-dahlen.com/","https://www.sveba-dahlen.com/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('rademaker', 'Rademaker', 'rademaker.com', 'NL', 'en', array['firin_teknoloji','pastacilik']::text[], 'vendor', true, null, 'rss', '["https://www.rademaker.com/","https://www.rademaker.com/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('mecatherm', 'Mecatherm', 'mecatherm.fr', 'FR', 'en', array['firin_teknoloji']::text[], 'vendor', true, null, 'rss', '["https://www.mecatherm.fr/","https://www.mecatherm.fr/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('diosna', 'DIOSNA (yoğurma/starter)', 'diosna.com', 'DE', 'en', array['firin_teknoloji','ekmek_fermantasyon']::text[], 'vendor', true, null, 'rss', '["https://www.diosna.com/","https://www.diosna.com/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('fimak', 'FİMAK Fırın Makinaları', 'fimak.com.tr', 'TR', 'tr', array['firin_teknoloji','turk_urunleri']::text[], 'vendor', true, null, 'rss', '["https://www.fimak.com.tr/","https://www.fimak.com.tr/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('porlanmaz', 'Porlanmaz Fırın Makinaları', 'porlanmaz.com', 'TR', 'tr', array['firin_teknoloji']::text[], 'vendor', true, null, 'rss', '["https://www.porlanmaz.com/","https://porlanmaz.com/"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('mateka', 'Mateka Ekipman', 'mateka.com.tr', 'TR', 'tr', array['firin_teknoloji']::text[], 'vendor', true, null, 'rss', '["https://www.mateka.com.tr/","https://mateka.com.tr/"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('lesaffre_tr', 'Lesaffre Türkiye', 'lesaffre.com.tr', 'TR', 'tr', array['ekmek_fermantasyon','turk_urunleri']::text[], 'vendor', true, 'lesaffre', 'rss', '["https://www.lesaffre.com.tr/","https://www.lesaffre.com.tr/feed/","https://www.lesaffre.com.tr/sitemap_index.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('ulker_pro', 'Ülker (kurumsal/inovasyon)', 'ulker.com.tr', 'TR', 'tr', array['pastacilik','sektor_gundemi']::text[], 'vendor', true, null, 'rss', '["https://www.ulker.com.tr/","https://www.ulker.com.tr/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('eti_kurumsal', 'ETİ (kurumsal)', 'etietieti.com', 'TR', 'tr', array['pastacilik']::text[], 'vendor', true, null, 'rss', '["https://www.etietieti.com/","https://www.etietieti.com/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('itu_gida', 'İTÜ Gıda Mühendisliği', 'gidamuh.itu.edu.tr', 'TR', 'tr', array['bilim_arge']::text[], 'academic', false, null, 'rss', '["https://gidamuh.itu.edu.tr/","https://gidamuh.itu.edu.tr/haberler"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('hacettepe_gida', 'Hacettepe Gıda Mühendisliği', 'fde.hacettepe.edu.tr', 'TR', 'tr', array['bilim_arge']::text[], 'academic', false, null, 'rss', '["https://fde.hacettepe.edu.tr/","http://www.fde.hacettepe.edu.tr/"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('ankara_gida', 'Ankara Üniversitesi Gıda Mühendisliği', 'eng.ankara.edu.tr', 'TR', 'tr', array['bilim_arge']::text[], 'academic', false, null, 'rss', '["https://eng.ankara.edu.tr/gida/","https://eng.ankara.edu.tr/"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('ege_gida', 'Ege Üniversitesi Gıda Mühendisliği', 'food.ege.edu.tr', 'TR', 'tr', array['bilim_arge']::text[], 'academic', false, null, 'rss', '["https://food.ege.edu.tr/","https://food.ege.edu.tr/tr-11821/duyurular.html"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('tse', 'Türk Standardları Enstitüsü (TSE)', 'tse.org.tr', 'TR', 'tr', array['hijyen_kalite','isletme']::text[], 'gov', false, null, 'rss', '["https://www.tse.org.tr/","https://www.tse.org.tr/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('tobb', 'TOBB', 'tobb.org.tr', 'TR', 'tr', array['isletme','sektor_gundemi']::text[], 'association', false, null, 'rss', '["https://www.tobb.org.tr/","https://www.tobb.org.tr/Sayfalar/AnaSayfa.php"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('iskur', 'İŞKUR (istihdam/teşvik)', 'iskur.gov.tr', 'TR', 'tr', array['isletme']::text[], 'gov', false, null, 'rss', '["https://www.iskur.gov.tr/","https://www.iskur.gov.tr/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('ibp_bbga_formula', 'BBGA Formula Exchange', 'bbga.org', 'US', 'en', array['ustalik_dunya','ekmek_fermantasyon']::text[], 'association', false, 'bbga', 'rss', '["https://www.bbga.org/formulas/"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('sourdough_lib', 'Puratos Sourdough Library', 'questforsourdough.com', 'BE', 'en', array['ekmek_fermantasyon','ustalik_dunya']::text[], 'vendor', true, 'puratos', 'rss', '["https://www.questforsourdough.com/","https://www.questforsourdough.com/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('theartisan_net', 'The Artisan (teknik ekmek arşivi)', 'theartisan.net', 'US', 'en', array['ustalik_dunya','ekmek_fermantasyon']::text[], 'archive', false, null, 'rss', '["http://www.theartisan.net/","http://theartisan.net/"]'::jsonb, 'candidate') on conflict (slug) do nothing;

-- Bot–kaynak eşleştirme: kaynak konuları → bot anahtarı (idempotent).
-- ASAMA-1 eki (2026-09-29): zayif konulara 16 yeni aday (isletme/turk_urunleri/ustalik_dunya).
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('snack_bakery', 'Snack Food & Wholesale Bakery', 'snackandbakery.com', 'US', 'en', array['isletme','sektor_gundemi']::text[], 'news', true, null, 'rss', '["https://snackandbakery.com/", "https://snackandbakery.com/feed/", "https://snackandbakery.com/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('bakers_journal', 'Bakers Journal', 'bakersjournal.com', 'CA', 'en', array['isletme','ustalik_dunya']::text[], 'news', true, null, 'rss', '["https://bakersjournal.com/", "https://bakersjournal.com/feed/", "https://bakersjournal.com/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('world_bakers', 'World Bakers', 'worldbakers.com', 'INT', 'en', array['isletme','sektor_gundemi']::text[], 'news', true, null, 'rss', '["https://worldbakers.com/", "https://worldbakers.com/feed/", "https://worldbakers.com/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('uno_tr', 'Uno Ekmek', 'uno.com.tr', 'TR', 'tr', array['turk_urunleri']::text[], 'vendor', true, null, 'rss', '["https://uno.com.tr/", "https://uno.com.tr/feed/", "https://uno.com.tr/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('torku', 'Torku', 'torku.com.tr', 'TR', 'tr', array['turk_urunleri']::text[], 'vendor', true, null, 'rss', '["https://torku.com.tr/", "https://torku.com.tr/feed/", "https://torku.com.tr/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('akmaya', 'Akmaya', 'akmaya.com.tr', 'TR', 'tr', array['turk_urunleri','ekmek_fermantasyon']::text[], 'vendor', true, null, 'rss', '["https://akmaya.com.tr/", "https://akmaya.com.tr/feed/", "https://akmaya.com.tr/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('ozmaya', 'Özmaya', 'ozmaya.com.tr', 'TR', 'tr', array['turk_urunleri','ekmek_fermantasyon']::text[], 'vendor', true, 'lesaffre', 'rss', '["https://ozmaya.com.tr/", "https://ozmaya.com.tr/feed/", "https://ozmaya.com.tr/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('ulusoy_un', 'Ulusoy Un', 'ulusoyun.com.tr', 'TR', 'tr', array['turk_urunleri','un_tahil']::text[], 'vendor', true, null, 'rss', '["https://ulusoyun.com.tr/", "https://ulusoyun.com.tr/feed/", "https://ulusoyun.com.tr/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('dunya_gida', 'Dünya Gıda', 'dunyagida.com.tr', 'TR', 'tr', array['turk_urunleri','sektor_gundemi']::text[], 'news', true, null, 'rss', '["https://dunyagida.com.tr/", "https://dunyagida.com.tr/feed/", "https://dunyagida.com.tr/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('gida_hatti', 'Gıda Hattı', 'gidahatti.com', 'TR', 'tr', array['sektor_gundemi','turk_urunleri']::text[], 'news', true, null, 'rss', '["https://gidahatti.com/", "https://gidahatti.com/feed/", "https://gidahatti.com/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('mauri_tr', 'AB Mauri Türkiye', 'mauri.com.tr', 'TR', 'tr', array['turk_urunleri','ekmek_fermantasyon']::text[], 'vendor', true, null, 'rss', '["https://mauri.com.tr/", "https://mauri.com.tr/feed/", "https://mauri.com.tr/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('perfect_loaf', 'The Perfect Loaf', 'theperfectloaf.com', 'US', 'en', array['ustalik_dunya','ekmek_fermantasyon']::text[], 'news', true, null, 'rss', '["https://theperfectloaf.com/", "https://theperfectloaf.com/feed/", "https://theperfectloaf.com/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('breadtopia', 'Breadtopia', 'breadtopia.com', 'US', 'en', array['ustalik_dunya','ekmek_fermantasyon']::text[], 'vendor', true, null, 'rss', '["https://breadtopia.com/", "https://breadtopia.com/feed/", "https://breadtopia.com/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('chainbaker', 'ChainBaker', 'chainbaker.com', 'UK', 'en', array['ustalik_dunya','ekmek_fermantasyon']::text[], 'news', false, null, 'rss', '["https://chainbaker.com/", "https://chainbaker.com/feed/", "https://chainbaker.com/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('weekend_bakery', 'Weekend Bakery', 'weekendbakery.com', 'NL', 'en', array['ustalik_dunya','pastacilik']::text[], 'archive', false, null, 'rss', '["https://weekendbakery.com/", "https://weekendbakery.com/feed/", "https://weekendbakery.com/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('bake_from_scratch', 'Bake from Scratch', 'bakefromscratch.com', 'US', 'en', array['pastacilik','ustalik_dunya']::text[], 'news', true, null, 'rss', '["https://bakefromscratch.com/", "https://bakefromscratch.com/feed/", "https://bakefromscratch.com/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;

insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('food_business_news', 'Food Business News', 'foodbusinessnews.net', 'US', 'en', array['isletme','sektor_gundemi']::text[], 'news', true, 'sosland', 'rss', '["https://foodbusinessnews.net/", "https://foodbusinessnews.net/feed/", "https://foodbusinessnews.net/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('americanbakers', 'American Bakers Association', 'americanbakers.org', 'US', 'en', array['isletme','sektor_gundemi']::text[], 'association', false, null, 'rss', '["https://americanbakers.org/", "https://americanbakers.org/feed/", "https://americanbakers.org/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('craft_bakers_uk', 'Craft Bakers Association', 'craftbakersassociation.co.uk', 'UK', 'en', array['isletme','ustalik_dunya']::text[], 'association', false, null, 'rss', '["https://craftbakersassociation.co.uk/", "https://craftbakersassociation.co.uk/feed/", "https://craftbakersassociation.co.uk/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('simfer', 'Simfer', 'simfer.com.tr', 'TR', 'tr', array['firin_teknoloji','turk_urunleri']::text[], 'vendor', true, null, 'rss', '["https://simfer.com.tr/", "https://simfer.com.tr/feed/", "https://simfer.com.tr/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('oztiryakiler', 'Öztiryakiler', 'oztiryakiler.com.tr', 'TR', 'tr', array['firin_teknoloji','turk_urunleri']::text[], 'vendor', true, null, 'rss', '["https://oztiryakiler.com.tr/", "https://oztiryakiler.com.tr/feed/", "https://oztiryakiler.com.tr/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;
insert into public.academy_sources (slug, name, domain, country, lang, topics, source_type, is_commercial, publisher_group, access_method, feed_urls, status) values ('degirmenci_dergisi', 'Değirmenci Dergisi', 'degirmencidergisi.com', 'TR', 'tr', array['un_tahil','turk_urunleri','sektor_gundemi']::text[], 'news', true, 'parantez', 'rss', '["https://degirmencidergisi.com/", "https://degirmencidergisi.com/feed/", "https://degirmencidergisi.com/sitemap.xml"]'::jsonb, 'candidate') on conflict (slug) do nothing;

insert into public.academy_bot_sources (bot_key, source_id, weight)
select t.topic, s.id, 100
from public.academy_sources s
cross join lateral unnest(s.topics) as t(topic)
join public.academy_bot_profiles b on b.bot_key = t.topic
on conflict (bot_key, source_id) do nothing;
